<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu-config [
<!ELEMENT MenuConfig (Displayers, Menus+)>
<!ELEMENT Displayers (Displayer+)>
<!ELEMENT Menus (Menu+)>
<!ELEMENT Displayer EMPTY>
<!ATTLIST Displayer
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT Menu (Item*)>
<!ATTLIST Menu
    name CDATA #REQUIRED
    title CDATA #REQUIRED
    description CDATA #IMPLIED
    page CDATA #IMPLIED
    width CDATA #IMPLIED
    image CDATA #IMPLIED
>
<!ELEMENT Item (Item*)>
<!ATTLIST Item
    name CDATA #REQUIRED
    title CDATA #REQUIRED
    description CDATA #IMPLIED
    page CDATA #IMPLIED
    width CDATA #IMPLIED
    image CDATA #IMPLIED
>
]>
<MenuConfig>
	<!-- Menu modelo Coolmenu usado como padrÃ£o -->
	<Displayers>
		<Displayer name="MenuSistema" type="net.sf.navigator.displayer.CoolMenuDisplayer4" />
	</Displayers>
	
	<Menus>
		<Menu name="MenuDepartamento" title="menu.departamento" description="dica.departamento.atualizar" page="/manterDepartamento.do?method=entrada" width="130" image="imagens/departamento.png" />
		<Menu name="MenuUsuario" title="menu.usuario" description="dica.usuario.atualizar" page="/manterUsuario.do?method=entrada" image="imagens/usuario.png" />
		<Menu name="MenuWorkflow" title="menu.workflow" image="imagens/workflow.png">
			<Item name="MenuWorkflowManter" title="menu.workflow.manter" width="110" page="/manterWorkflow.do?method=entrada" />
			<Item name="MenuWorkflowRegistros" title="menu.workflow.registros" width="110">
				<Item name="MenuWorkflowAtivos" title="menu.workflow.registros.ativos" width="110" page="/usarWorkflow.do?method=entrada" />
				<Item name="MenuWorkflowFinalizados" title="menu.workflow.registros.finalizados" width="110" page="/usarWorkflow.do?method=entradaFinalizados" />
			</Item>
		</Menu>
		<Menu name="MenuSair" title="menu.sair" description="dica.sair" page="/dologin?logout=true" image="imagens/sair.png"/>
	</Menus>
	
</MenuConfig>